use std::io::Write;
use std::path::PathBuf;

use clap::Parser;
use rsomics_common::{CommonFlags, Result, RsomicsError, Tool, ToolMeta};

use rsomics_rnaseq_metrics::{
    GeneIndex, StrandSpecificity, collect_metrics, compute_bias, format_metrics, load_refflat,
    load_rrna_intervals,
};
use std::collections::HashMap;

pub const META: ToolMeta = ToolMeta {
    name: env!("CARGO_PKG_NAME"),
    version: env!("CARGO_PKG_VERSION"),
};

#[derive(Parser, Debug)]
#[command(
    name = "rsomics-rnaseq-metrics",
    version,
    about = "RNA-seq QC metrics (region base counts, strand bias, transcript-coverage bias)",
    long_about = None,
    disable_help_flag = true
)]
pub struct Cli {
    /// Input coordinate-sorted BAM file.
    #[arg(short = 'i', long = "input")]
    pub input: PathBuf,

    /// Output file (Picard-format metrics text).
    #[arg(short = 'o', long = "output")]
    pub output: PathBuf,

    /// refFlat gene model file.
    #[arg(short = 'r', long = "ref-flat")]
    pub ref_flat: PathBuf,

    /// Ribosomal `interval_list` (Picard format). If omitted, `RIBOSOMAL_BASES` column is blank.
    #[arg(long = "ribosomal-intervals")]
    pub ribosomal_intervals: Option<PathBuf>,

    /// Strand specificity of the library.
    #[arg(
        short = 's',
        long = "strand-specificity",
        default_value = "NONE",
        value_parser = |s: &str| s.parse::<StrandSpecificity>().map_err(|e| e)
    )]
    pub strand_specificity: StrandSpecificity,

    /// Minimum transcript mRNA length to include in bias calculation.
    #[arg(long = "minimum-length", default_value_t = 500)]
    pub minimum_length: u64,

    #[command(flatten)]
    pub common: CommonFlags,
}

impl Cli {
    fn run_inner(self) -> Result<()> {
        let genes = load_refflat(&self.ref_flat)?;
        if genes.is_empty() {
            return Err(RsomicsError::InvalidInput(
                "refFlat contains no gene models".into(),
            ));
        }
        eprintln!(
            "[rsomics-rnaseq-metrics] Loaded {} gene models",
            genes.len()
        );

        let rrna = if let Some(ref path) = self.ribosomal_intervals {
            load_rrna_intervals(path)?
        } else {
            HashMap::new()
        };
        let has_rrna = self.ribosomal_intervals.is_some();

        let gene_index = GeneIndex::new(genes);

        eprintln!(
            "[rsomics-rnaseq-metrics] Processing {}",
            self.input.display()
        );

        let metrics = collect_metrics(&self.input, &gene_index, &rrna, self.strand_specificity)?;

        let bias = compute_bias(&self.input, &gene_index, self.minimum_length)?;

        let content = format_metrics(&metrics, &bias, has_rrna);

        let mut out = std::fs::File::create(&self.output).map_err(|e| {
            RsomicsError::Io(std::io::Error::other(format!(
                "creating {}: {e}",
                self.output.display()
            )))
        })?;

        // Write Picard-format header preamble (invocation-agnostic lines only).
        writeln!(out, "## htsjdk.samtools.metrics.StringHeader")?;
        writeln!(
            out,
            "# rsomics-rnaseq-metrics {}",
            env!("CARGO_PKG_VERSION")
        )?;
        writeln!(out, "## htsjdk.samtools.metrics.StringHeader")?;
        writeln!(out, "# Generated by rsomics-rnaseq-metrics")?;
        writeln!(out)?;
        writeln!(out, "## METRICS CLASS\tpicard.analysis.RnaSeqMetrics")?;
        write!(out, "{content}")?;

        Ok(())
    }
}

impl Tool for Cli {
    fn meta() -> ToolMeta {
        META
    }

    fn common(&self) -> &CommonFlags {
        &self.common
    }

    fn execute(self) -> Result<()> {
        self.run_inner()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn cli_debug_assert() {
        Cli::command().debug_assert();
    }
}
