[package]
name = "rsomics-fastx-convert"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Convert between FASTA/FASTQ formats: fq2fa, fa2fq, fx2tab, tab2fx, Phred quality re-encoding"

[[bin]]
name = "rsomics-fastx-convert"
path = "src/main.rs"

[lib]
name = "rsomics_fastx_convert"
path = "src/lib.rs"
doctest = false

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true

[dependencies]
rsomics-common = { version = "0.6" }
clap = { workspace = true }
anyhow = { workspace = true }
needletail = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = "3"
