[package]
name = "rsomics-vcf-sample-concordance"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Sample concordance between VCF callsets"
[[bin]]
name = "rsomics-vcf-sample-concordance"
path = "src/main.rs"
[dependencies]
rsomics-common = { path = "../../../foundation/rsomics-common", version = "0.5" }
rsomics-help = { path = "../../../foundation/rsomics-help", version = "0.3" }
clap.workspace = true
[lints]
workspace = true
