/// Compatibility test against MethylDackel 0.6.1 `extract` output.
///
/// Compares our bedGraph output line-by-line (after header) against
/// a golden file generated by `MethylDackel extract … -q 2`.
///
/// The test self-skips when:
/// - The golden fixture is absent (stripped test env).
/// - MethylDackel binary is not on PATH (CI without the upstream).
use std::path::PathBuf;
use std::process::Command;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

fn methyldackel_available() -> bool {
    // Check common install locations.
    Command::new("MethylDackel")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
        || Command::new("/tmp/MethylDackel_build/MethylDackel")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
}

fn find_methyldackel() -> Option<String> {
    if Command::new("MethylDackel")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
    {
        return Some("MethylDackel".into());
    }
    let local = "/tmp/MethylDackel_build/MethylDackel";
    if std::path::Path::new(local).exists()
        && Command::new(local)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    {
        return Some(local.into());
    }
    None
}

fn data_lines(content: &str) -> Vec<&str> {
    content
        .lines()
        .filter(|l| !l.starts_with("track "))
        .collect()
}

/// Run ours and MethylDackel on the same fixture with the same flags, then
/// compare bedGraph data lines exactly.
fn run_compat(min_mapq: u8) {
    if !methyldackel_available() {
        eprintln!("SKIP: MethylDackel not found");
        return;
    }
    let fixtures = fixture_dir();
    let ref_fa = fixtures.join("cg100.fa");
    let bam = fixtures.join("cg_aln.bam");
    if !ref_fa.exists() || !bam.exists() {
        eprintln!("SKIP: golden fixtures not found");
        return;
    }

    let tmp = tempfile::tempdir().expect("tempdir");
    let our_prefix = tmp.path().join("our").to_string_lossy().into_owned();
    let md_prefix = tmp.path().join("md").to_string_lossy().into_owned();

    // Run ours.
    let binary = env!("CARGO_BIN_EXE_rsomics-methyldackel");
    let status = Command::new(binary)
        .args([
            ref_fa.to_str().unwrap(),
            bam.to_str().unwrap(),
            "-o",
            &our_prefix,
            "--min-mapq",
            &min_mapq.to_string(),
            "--min-phred",
            "5",
        ])
        .status()
        .expect("rsomics-methyldackel failed to launch");
    assert!(status.success(), "rsomics-methyldackel exited non-zero");

    // Run MethylDackel.
    let md = find_methyldackel().unwrap();
    let md_status = Command::new(&md)
        .args([
            "extract",
            ref_fa.to_str().unwrap(),
            bam.to_str().unwrap(),
            "-o",
            &md_prefix,
            "-q",
            &min_mapq.to_string(),
            "-p",
            "5",
        ])
        .status()
        .expect("MethylDackel failed to launch");
    assert!(md_status.success(), "MethylDackel exited non-zero");

    let our_out =
        std::fs::read_to_string(format!("{our_prefix}_CpG.bedGraph")).expect("ours output missing");
    let md_out = std::fs::read_to_string(format!("{md_prefix}_CpG.bedGraph"))
        .expect("MethylDackel output missing");

    let our_lines = data_lines(&our_out);
    let md_lines = data_lines(&md_out);

    assert_eq!(
        our_lines.len(),
        md_lines.len(),
        "line count mismatch: ours={} MethylDackel={}\nours:\n{}\nMD:\n{}",
        our_lines.len(),
        md_lines.len(),
        our_out,
        md_out
    );

    for (i, (ours, md)) in our_lines.iter().zip(md_lines.iter()).enumerate() {
        assert_eq!(
            ours,
            md,
            "line {} mismatch:\n  ours: {}\n  MD:   {}",
            i + 1,
            ours,
            md
        );
    }
}

#[test]
fn compat_cg100_q2() {
    run_compat(2);
}

/// With default minMapq=10 all reads in cg_aln.bam (MAPQ=6) are filtered
/// → only the header line is emitted. Verify ours matches.
#[test]
fn compat_cg100_q10_no_output() {
    run_compat(10);
}

/// Compare against the pre-generated golden bedGraph (MethylDackel 0.6.1, -q 2).
/// This test runs without MethylDackel being installed.
#[test]
fn golden_cg100_q2() {
    let fixtures = fixture_dir();
    let ref_fa = fixtures.join("cg100.fa");
    let bam = fixtures.join("cg_aln.bam");
    let golden = fixtures.join("golden_out_CpG.bedGraph");
    if !ref_fa.exists() || !bam.exists() || !golden.exists() {
        eprintln!("SKIP: golden fixtures not found");
        return;
    }

    let tmp = tempfile::tempdir().expect("tempdir");
    let our_prefix = tmp.path().join("our").to_string_lossy().into_owned();

    let binary = env!("CARGO_BIN_EXE_rsomics-methyldackel");
    let status = Command::new(binary)
        .args([
            ref_fa.to_str().unwrap(),
            bam.to_str().unwrap(),
            "-o",
            &our_prefix,
            "--min-mapq",
            "2",
            "--min-phred",
            "5",
        ])
        .status()
        .expect("rsomics-methyldackel failed to launch");
    assert!(status.success(), "rsomics-methyldackel exited non-zero");

    let our_out =
        std::fs::read_to_string(format!("{our_prefix}_CpG.bedGraph")).expect("ours output missing");
    let golden_out = std::fs::read_to_string(&golden).expect("golden file missing");

    let our_lines = data_lines(&our_out);
    let golden_lines = data_lines(&golden_out);

    assert_eq!(
        our_lines.len(),
        golden_lines.len(),
        "line count mismatch: ours={} golden={}\nours:\n{}\ngolden:\n{}",
        our_lines.len(),
        golden_lines.len(),
        our_out,
        golden_out
    );

    for (i, (ours, gold)) in our_lines.iter().zip(golden_lines.iter()).enumerate() {
        assert_eq!(
            ours,
            gold,
            "line {} mismatch:\n  ours:   {}\n  golden: {}",
            i + 1,
            ours,
            gold
        );
    }
}
